# Generated by Django 5.1 on 2025-08-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
    ]
