# Generated by Django 5.1 on 2025-08-31 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qtde',
            new_name='quantidade',
        ),
    ]
